/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mercado.conexao;
import DAO.ProdutoDAO;
import beans.Produto;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author laboratorio
 */
public class CadastroProdutos extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProdutos
     */
    private ProdutoDAO produtoDAO = new ProdutoDAO();

    public CadastroProdutos() {
        initComponents();
        setSize(450, 400);
        setLocationRelativeTo(null);
    }
 
    private int gerarId() {
        Random random = new Random();
        return random.nextInt(1000) + 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblPreço = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        btnCriar = new javax.swing.JButton();
        btnLer = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        lblQuantidade1 = new javax.swing.JLabel();
        lblQuantidade2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(211, 211, 211));
        jLabel1.setText("CADASTRO DE PRODUTOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 550, 48);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(211, 211, 211));
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 70, 60, 16);

        txtNome.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        getContentPane().add(txtNome);
        txtNome.setBounds(130, 60, 170, 30);

        lblPreço.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblPreço.setForeground(new java.awt.Color(211, 211, 211));
        lblPreço.setText("Preço:");
        getContentPane().add(lblPreço);
        lblPreço.setBounds(80, 100, 60, 16);

        txtPreco.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        getContentPane().add(txtPreco);
        txtPreco.setBounds(130, 100, 170, 30);

        lblQuantidade.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblQuantidade.setForeground(new java.awt.Color(211, 211, 211));
        lblQuantidade.setText("Quantidade:");
        getContentPane().add(lblQuantidade);
        lblQuantidade.setBounds(40, 220, 90, 19);

        txtQuantidade.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        getContentPane().add(txtQuantidade);
        txtQuantidade.setBounds(130, 220, 170, 30);

        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCriar);
        btnCriar.setBounds(130, 300, 76, 27);

        btnLer.setText("Ver");
        btnLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLerActionPerformed(evt);
            }
        });
        getContentPane().add(btnLer);
        btnLer.setBounds(130, 270, 76, 27);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(220, 270, 80, 27);

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletar);
        btnDeletar.setBounds(220, 300, 80, 27);

        lblQuantidade1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblQuantidade1.setForeground(new java.awt.Color(211, 211, 211));
        lblQuantidade1.setText("Código:");
        getContentPane().add(lblQuantidade1);
        lblQuantidade1.setBounds(70, 140, 60, 19);

        lblQuantidade2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblQuantidade2.setForeground(new java.awt.Color(211, 211, 211));
        lblQuantidade2.setText("Descrição:");
        getContentPane().add(lblQuantidade2);
        lblQuantidade2.setBounds(50, 180, 80, 19);

        txtCodigo.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(130, 140, 170, 30);

        txtDescricao.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescricao);
        txtDescricao.setBounds(130, 180, 170, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/mercado.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-10, 0, 440, 360);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 430, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limparFormulario(){
        txtCodigo.setText("");
        txtDescricao.setText("");
        txtNome.setText("");
        txtPreco.setText("");
        txtQuantidade.setText("");
    }
    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        // TODO add your handling code here:
           try {
        String codigo = txtCodigo.getText();
        String nome = txtNome.getText();
        String descricao = txtDescricao.getText();
        double preco = Double.parseDouble(txtPreco.getText());
        int quantidade = Integer.parseInt(txtQuantidade.getText());

        Produto produto = new Produto(codigo, nome, descricao, preco, quantidade);
        produtoDAO.inserir(produto);

        JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao cadastrar produto: " + e.getMessage());
    }
    limparFormulario();
    }//GEN-LAST:event_btnCriarActionPerformed
    
    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
    String codigo = txtCodigo.getText();

    int confirm = JOptionPane.showConfirmDialog(null, "Deseja realmente deletar o produto?", "Confirmação", JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        produtoDAO.deletarProduto(codigo);
        JOptionPane.showMessageDialog(this, "Produto deletado com sucesso!");
    }    
    limparFormulario();
    }//GEN-LAST:event_btnDeletarActionPerformed
 
    
               
    private void btnLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLerActionPerformed
      
         String codigo = txtCodigo.getText();
    Produto produto = produtoDAO.buscarProduto(codigo);

    if (produto != null) {
        txtNome.setText(produto.getNome());
        txtDescricao.setText(produto.getDescricao());
        txtPreco.setText(String.valueOf(produto.getPreco()));
        txtQuantidade.setText(String.valueOf(produto.getQuantidade()));
    } else {
        JOptionPane.showMessageDialog(this, "Produto não encontrado.");
    }
    }//GEN-LAST:event_btnLerActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        try {
        String codigo = txtCodigo.getText();
        Produto produto = produtoDAO.buscarProduto(codigo);

        if (produto != null) {
            produto.setNome(txtNome.getText());
            produto.setDescricao(txtDescricao.getText());
            produto.setPreco(Double.parseDouble(txtPreco.getText()));
            produto.setQuantidade(Integer.parseInt(txtQuantidade.getText()));

            produtoDAO.atualizarProduto(produto);
            JOptionPane.showMessageDialog(this, "Produto atualizado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Produto não encontrado.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao atualizar produto.");
    }
    limparFormulario();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnLer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblPreço;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblQuantidade1;
    private javax.swing.JLabel lblQuantidade2;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
